/* eslint-disable */

// This file is auto-generated by @tanstack/router-plugin
// Do not edit this file manually

import { Route as rootRoute } from './routes/__root'
import { Route as UsersRoute } from './routes/users'
import { Route as IndexRoute } from './routes/index'

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRoute
      parentRoute: typeof rootRoute
    }
  }
}

Object.assign(IndexRoute.options, {
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
})

Object.assign(UsersRoute.options, {
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
})

export const routeTree = rootRoute.addChildren([IndexRoute, UsersRoute])

